### ISSUE TITLE
Handle &, <, and > correctly

### ISSUE THREAD

**Issue by ddbruce** [rpiambulance/slack-poll#14]
This is pending Slack fixing their side of things (see @lramos15 for the support request status on that).

`&`, `<`, and `>` are not handled correctly on the desktop app, if I'm correct.

**Comment by ddbruce** [comment]
@lramos15 any update on this?

**Comment by lramos15** [comment]
Slack has a bug I assume it'll take awhile.

**Comment by ddbruce** [comment]
@lramos15 we discussed this recently. Any update?

**Comment by lramos15** [comment]
It's still wonky but we have implemented fixes so you can't really tell slack is off. I'll close it for now
