### ISSUE TITLE
npm start should transpile to JavaScript

### ISSUE THREAD

**Issue by ddbruce** [rpiambulance/slack-poll#28]
**Is your feature request related to a problem? Please describe.**
`npm start` may not actually "start" the application.

**Describe the solution you'd like**
`npm start` should run `npm run compile` as part of its flow.

**Describe alternatives you've considered**
Running the commands seperately? Idk, this is more for efficiency and normalcy's sake.

**Comment by MasterOdin** [comment]
Done in #29
